#lang racket
(define (flaplist lst)
  (if (pair?  lst)
      (append (flaplist (cdr lst)) (list (car lst)))
      (if (null? lst)
          '()
          (list lst))))
(define (main)
  (define p (read))
  (if (eq? p eof)
      (void)
      (begin(display (flaplist p))
       (newline)
       (main)
       (void))))
(main)