#lang racket
(define (flat-map lst)
  (cond((null? lst) '())
       ((pair? lst) (append (flat-map (car lst))(flat-map (cdr lst))))
       (else (list lst))))
(define (main)
  (define p (read))
  (if (eq? p eof)
      (void)
      (begin(display (flat-map p))
            (newline)
            (main)
            (void))))
(main)